version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - varnish
    networks:
      - frontend

  varnish:
    image: varnish:latest
    container_name: varnish
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl
    depends_on:
      - flask
    networks:
      - frontend
      - backend

  flask:
    image: python:3.8-slim
    container_name: flask
    volumes:
      - ./app.py:/app/app.py
    working_dir: /app
    command: sh -c "pip install flask requests && python app.py"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
